### ISSUE TITLE
crashed when put it on toggle

### ISSUE THREAD

**Issue by Blackie-coke** [Seconb/Arsenal-Colorbot#5]
when i put it on toggle mode its always crashed for some reason

**Comment by TaylorIsBlue** [comment]
This is fixed in my pull req, i had the same issue and decided to fix it myself.
The problem was it couldn't initiate the beeping noise, so i just removed it as a temp fix till the creator gets to it.

You can use my pull req (after reviewing the code if you don't trust it which is understandable) by:
1. installing python
2. open admin command prompt (to prevent any security issues)
3. cloning my repo with git clone (url.git) in command prompt
4. in terminal do _python aimsource.py_ or whatever the file is called, it may ask you to install a module.
5. if you need to install the modules, do pip install (module) in command prompt. CV2 is not a module by the way, if its asking you to install that, install pip install opencv-python


THIS is a temporary solution, i may have a .exe already released by the time you see this to make things easier

**Comment by Seconb** [comment]
> This is fixed.

the compiled version isnt fixed because im lazy
